---
title: "Analysis"
author: "Derek Brickley"
date: "1/26/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library(MASS)
library(gridExtra)  
library(mnormt) 
library(lme4) 
library(knitr) 
library(kableExtra)
library(tidyverse)
library(GGally)
library(mice)
library(nlme)
library(boot)
library(HLMdiag)
library(pander)
library(skimr)
library(udpipe)
```

```{r}
sports <- read.csv("Full_Data.csv")
```

```{r}
sports <- sports %>% select(-FBS.or.FCS) %>%
  separate(Academic.Year, c("Start.Year", "End.Year")) %>%
  mutate(Start.Year = as.numeric(Start.Year)) %>%
  mutate(End.Year = as.numeric(End.Year))

sports$program.id <- unique_identifier(sports, fields = c("School", "Sport"))
head(sports, 15)
range(sports$program.id)

sports <- sports %>% mutate(Years10 = Start.Year - 2010)

skim(sports)
```

```{r}
sports %>% count(School)
sports %>% count(Start.Year)
```


```{r}
select <- dplyr::select
keydata <- sports %>% 
  dplyr::select(Rank, W, L, T, program.id
      Pct, Start.Year, Sport, School, State, Multi.Year.APR, Penalties, Postseason)
keydata
# Create Level2 data set by picking off one observation 
# per subject, which would be easier if every subject 
# had a diary entry labeled '1' - should be 37 rows 
# and 6 columns (one per L2 variable)
school.lev2 <-  keydata %>%
  group_by(School) %>%
  filter(row_number() == 1) %>%
  select(School, Start.Year)

year.lev2 <-  keydata %>%
  group_by((Start.Year)) %>%
  filter(row_number() == 1) %>%
  select(School, Start.Year)
```

```{r}
meanbyschool <- sports %>% group_by(School) %>%
  summarise(meanbyschool = mean(Multi.Year.APR, na.rm = TRUE))
school.lev2 <- school.lev2 %>%
  left_join(meanbyschool, by = "School")

meanbyyear <- sports %>% group_by(Start.Year) %>%
  summarise(meanbyyear = mean(Multi.Year.APR, na.rm = TRUE))
year.lev2 <- year.lev2 %>%
  left_join(meanbyyear, by = "Start.Year")
```

```{r}
sports %>% count(Sport)
```

```{r}
theme.1 <- theme(axis.title.x = element_text(size = 14),
  axis.title.y = element_text(size = 14),
  plot.title=element_text(hjust=.9,face="italic",size=12))
## Histogram of negative affect frequencies
apr.all <- ggplot(data=sports,aes(x=Multi.Year.APR)) + 
  geom_histogram(binwidth = 20, fill = "white",color = "black") + 
  theme.1 + xlim(400,1000) +
  xlab("Multi Year APR Score") + ylab("Frequency") + labs(title="(a)") 

apr.mean <- ggplot(data=school.lev2,aes(x=meanbyschool)) + 
  geom_histogram(binwidth = 20, fill = "white", 
                 color = "black") + 
  theme.1 + xlim(800,1000) +
  xlab("Mean APR Score by School") + ylab("Frequency") + labs(title="(b)") 

year.apr.mean <- ggplot(data=year.lev2,aes(x=meanbyyear)) + 
  geom_histogram(binwidth = 20, fill = "white", 
                 color = "black") + 
  theme.1 + xlim(800,1000) +
  xlab("Mean APR Score by Year") + ylab("Frequency") + labs(title="(c)") 
mli.hist1 <- grid.arrange(apr.all,apr.mean,year.apr.mean, ncol=1)
```

```{r}
box.sport <- ggplot(data=sports,aes(factor(Sport),Multi.Year.APR)) +
  geom_boxplot() + 
  theme.1 + coord_flip() + ylab("Multi-Year APR") + 
  xlab("") + labs(title="(a)")

mli.boxscatmat1 <- grid.arrange(box.sport,ncol=1)
```

```{r}
ggplot(sports,aes(x=Start.Year,y=Multi.Year.APR)) +
  geom_smooth(method= "lm", color = "black") + 
  labs(x="Academic Year",y="Multi-Year APR Score") +
  theme.1
```

```{r}
set.seed(1313)
randteam = as.vector(sample(sports$program.id,size=25))
sportsrd <- sports %>%
  filter(program.id %in% randteam)
ggplot(sportsrd, aes(x=Start.Year, y=Multi.Year.APR)) + 
  facet_wrap(~program.id,ncol=5) + 
  geom_point() + 
  geom_smooth(method="lm") + 
  theme.1 +
  theme(strip.text.x=element_blank()) + 
  labs(x="Academic Year",y="Multi-Year APR Score")
```

```{r}
### Unconditional Means Model
model1 <- lmer(Multi.Year.APR ~ 1 + (1|program.id) + (1|School), 
               REML=T, data=sports)

VCrandom <- VarCorr(model1)
print(VCrandom, comp = c("Variance", "Std.Dev."))
cat(" Number of Level Two groups = ",
    summary(model1)$ngrps[1], "\n", 
    "Number of Level Three groups = ",
    summary(model1)$ngrps[2])
coef(summary(model1))
```

```{r}
### Unconditional Growth Model
model2 = lmer(Multi.Year.APR ~ Years10 + (Years10|program.id) + (Years10|School),
               REML=T, data=sports)

VCrandom <- VarCorr(model2)
print(VCrandom, comp = c("Variance", "Std.Dev."))
cat(" Number of Level Two groups = ",
    summary(model2)$ngrps[1], "\n", 
    "Number of Level Three groups = ",
    summary(model2)$ngrps[2])
coef(summary(model2))
```